# Generated by Django 5.2.14 on 2026-05-18 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_game', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit via Razorpay'), ('WITHDRAW', 'Withdraw to Bank/UPI'), ('GAME_ENTRY', 'Entry Fee Deducted'), ('GAME_WIN', 'Prize Money Added'), ('REFUND', 'Match Draw Refund')], max_length=20),
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('wpm', models.IntegerField(blank=True, default=0, null=True)),
                ('accuracy', models.IntegerField(blank=True, default=100, null=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('prize_won', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_records', to='core_game.gametable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
