# Generated by Django 5.2.14 on 2026-05-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_game', '0003_alter_transaction_tx_type_matchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit via Razorpay'), ('WITHDRAW', 'Withdraw to Bank/UPI'), ('GAME_ENTRY', 'Entry Fee Deducted'), ('GAME_WIN', 'Prize Money Added')], max_length=20),
        ),
    ]
