# Generated by Django 5.2.14 on 2026-05-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_game', '0004_transaction_upi_id_alter_transaction_tx_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core_game.transaction',),
        ),
    ]
