# Generated by Django 5.2.14 on 2026-05-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_game', '0005_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='live_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
