# Generated by Django 5.2.14 on 2026-05-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_game', '0006_userprofile_live_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gamer_tag',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
