# Generated by Django 5.2.14 on 2026-05-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_game', '0007_userprofile_firebase_uid_userprofile_gamer_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='questions_count',
            field=models.IntegerField(default=5, help_text='इस टेबल में कितने सवाल होंगे?'),
        ),
        migrations.AddField(
            model_name='gametable',
            name='time_per_question',
            field=models.IntegerField(default=12, help_text='हर सवाल के लिए कितने सेकंड मिलेंगे?'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit via Razorpay'), ('WITHDRAW', 'Withdraw to Bank/UPI'), ('GAME_ENTRY', 'Entry Fee Deducted'), ('GAME_WIN', 'Prize Money Added'), ('BONUS', 'Daily Bonus Added'), ('REFUND', 'Game Tied Refund')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
